name: calendar_time
description: Implementation of MomentJS's calendar time, plus a bunch of other helper methods.
version: 2.0.0-nullsafety.0
homepage: https://github.com/rknell/calendar_time

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  intl: ^0.18.1

dev_dependencies:
  test:
  pedantic: ^1.9.2
